name: TriOne
options:
  bundleIdPrefix: com.trione
  xcodeVersion: "15.0"
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "5.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  TriOne:
    type: application
    platform: iOS
    sources:
      - TriOne
    settings:
      base:
        INFOPLIST_FILE: TriOne/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.trione.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    entitlements:
      path: TriOne/TriOne.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    # Note: Sign in with Apple requires paid Apple Developer Program
    # Add this back when you have a paid account:
    # com.apple.developer.applesignin:
    #   - Default
    dependencies:
      - package: GoogleSignIn
      - package: Supabase
        product: Supabase
      - package: RevenueCat
        product: RevenueCat

schemes:
  TriOne:
    build:
      targets:
        TriOne: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

